version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      - POSTGRES_USER: admin
      - POSTGRES_PASSWORD: password
      - POSTGRES_DB: mydatabase
    networks:
      - pgnetwork
    volumes:
      - pgdata:/var/lib/postgresql/data

    admin:
      image: dpage/pgadmin4:latest
      container_name: pgadmin
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com 
        PGADMIN_DEFAULT_PASSWORD: password
      depends_on:
        - db
      ports:
        - "8080:80"
      networks:
        - pgnetwork

networks:
  pgnetwork:
    driver: bridge

volumes:
  pgdata:
